apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gardener.cloud:authentication:oidc-webhook-authenticator
  labels:
    {{- include "oidc-webhook-authenticator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - authentication.gardener.cloud
  resources:
  - openidconnects
  verbs:
  - get
  - list
  - watch