# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

virtualGarden:
  enabled: false
  user:
    name: ""

webhookConfig:
  # CA bundle used to verify the webhook server certificate.
  # If global.certManager.enabled is set to `true` then `caBundle` value will be ignored.
  caBundle: |
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
