apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    insecure-skip-tls-verify: true
    server: https://control-plane.minikube.internal:10443/validate-token # the kube-apiserver cannot use cluster-dns
users:
- name: client
  user: {}
current-context: webhook
contexts:
- context:
    cluster: local
    user: client
  name: webhook
