images:
- name: oidc-webhook-authenticator
  sourceRepository: github.com/gardener/oidc-webhook-authenticator
  repository: eu.gcr.io/gardener-project/gardener/oidc-webhook-authenticator
  tag: "latest"
